import Head from "next/head";
import { Footer } from "../components/Fotter";
import styles from "../styles/Home.module.css";
import { Main } from "../components/Main";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main page="about" />
      <Footer />
    </div>
  );
}
