import Head from "next/head";
import { Links } from "../components/Links";
import { Footer } from "../components/Fotter";
import styles from "../styles/Home.module.css";
import { Headline } from "../components/Headline";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline page="about" />
        <Links />
      </main>
      <Footer />
    </div>
  );
}
